city: Oakland, California, US
year: 2026
conference_dates: October 5<sup>th</sup> - October 7<sup>th</sup> 2026
venue_url: https://conf.researchr.org/track/splash-issta-2026/splash-issta-2026-rebase-industry-track
past_editions:
  - 2020
  - 2021-ECOOP
  - 2021-SPLASH
  - 2024
  - 2025

# Possible states for cfp and registration: hidden, inactive,
# active and sold_out (for registration only). cfp_date
# and registration_date is displayed below the button if
# present and the state is set to inactive
cfp: hidden
cfp_date:
cfp_form:

registration: hidden
registration_url:
registration_date:

# Control different sections on the HP
show_about: true
show_organizers: false
show_recordings: false
show_sponsors: false
show_stream: false
show_zoom: false
show_talks: false

# Footer contact details. Comment out to hide
footer_email: aftandilian@gmail.com, dlehmann@google.com, filip.krikava@fit.cvut.cz
#footer_twitter: rebase_conf

# Liquid can't create arrays
empty_array: []
